### ISSUE TITLE
Failed to install boost library

### ISSUE THREAD

**Issue by guomingz** [ctuning/ck-request-asplos18-caffe-intel#14]
Hi folks,

i just followed the instructions from the [https://github.com/ctuning/ck-request-asplos18-caffe-intel ](url).

When i executed `ck install package:lib-caffe-intel-request-cpu`, specifically, i was blocked on the boost lib installation. The error messages is as below:
_Downloading package from '**https://github.com/intel/caffe/boost_1_64_0.tar.bz2**' ...
--2018-02-26 21:10:37--  https://github.com/intel/caffe/boost_1_64_0.tar.bz2
Resolving child-prc.intel.com (child-prc.intel.com)... 10.239.4.160
Connecting to child-prc.intel.com (child-prc.intel.com)|10.239.4.160|:913... connected.
Proxy request sent, awaiting response... 404 Not Found
2018-02-26 21:10:38 ERROR 404: Not Found.
_

It's weird that boost would be downloaded from Intel caffe github site. Why?

Besides, when u will complete the ck integration? i noticed there're 2 PR need to be integrated.

**Comment by Chunosov** [comment]
When I try to reproduce error an a clean system, I see similar error but with another dep:
```
Downloading package from 'https://github.com/intel/caffe/cmake-3.7.2-Linux-x86_64.tar.gz' ...
--2018-02-27 10:46:37--  https://github.com/intel/caffe/cmake-3.7.2-Linux-x86_64.tar.gz
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-02-27 10:46:37 ERROR 404: Not Found.
```

**Comment by Chunosov** [comment]
I've found the reason - https://github.com/ctuning/ck-env/issues/65, but not sure how to fix it properly...
As a workaround you have to install all the deps manually.

**Comment by guomingz** [comment]
Thanks @Chunosov  for your quick reply.

Your founding gave me an idea, or concern that does CK  system assume the original project should provide all its dependency packages on the project homepage too? If so, it's very hard to fix it.

**Comment by Chunosov** [comment]
No. A ck-package only enumerates deps as references to another ck-packages, and those provide information about how they can be installed, e.g. download link. So original project have not to host anything.

**Comment by gfursin** [comment]
Hello all! I am looking at the issue - it might be one of my latest changes that accidentally broke workflow... Will tell you shortly ...

**Comment by gfursin** [comment]
Yes, indeed, it was a bug in my latest commit (I tried to improve replay) - very sorry about that. Please just do:
```
$ ck pull repo:ck-env
```
and then try again:
```
$ ck install package:lib-caffe-intel-request-cpu
```
Things should hopefully work now!

Once again, really sorry for this @bug. However that's how we fix and improve our common workflows ;) ...

**Comment by gfursin** [comment]
We plan to commit pull request today/tomorrow (just were off site last two days) ...

**Comment by guomingz** [comment]
Thanks @gfursin.i’ll have a try locally later

**Comment by psyhtest** [comment]
@guomingz Have you had a chance to give it a try?

**Comment by guomingz** [comment]
@psyhtest  sorry, i didn't try it locally due to bandwidth issue. Please close this issue firstly.
