### ISSUE TITLE
Question about "-phase TEST" in caffe benchmarking command line

### ISSUE THREAD

**Issue by gfursin** [ctuning/ck-request-asplos18-caffe-intel#17]
Hi @guomingz!

I finally managed to run Intel Caffe on AWS with c5.9xlarge image and I see speedups of int8 vs fp32 

```
----------------------------------------------------------------------------------------------------
                                               SSD         ResNet-50         Inception-V3
----------------------------------------------------------------------------------------------------
BVLC_Caffe                                     N/A          N/A          N/A
----------------------------------------------------------------------------------------------------
FP32 BaseLine                                  N/A          N/A          N/A
----------------------------------------------------------------------------------------------------
+Folded BatchNorm                              31.5          192.6          146.1
----------------------------------------------------------------------------------------------------
+Fused Convolution and ReLU                    34.3          201.5          175.7
----------------------------------------------------------------------------------------------------
+Remove Sparsity                               34.0          226.8          175.2
----------------------------------------------------------------------------------------------------
+Fused Convolution and Element-wise Sum        34.1          310.9          175.4
----------------------------------------------------------------------------------------------------
+8-bit Low Precision                           42.8          460.3          280.7
```

However, I noticed that you use extra command line "-phase TEST" when running Caffe, which we didn't use in our tests. When I add it to our CK workflow, I also see speedups:
```
$ ck run program:caffe --extra_run_cmd="-phase TEST"
```

However, my question is the following: what does this flag do? I thought that when we use "test" command for Caffe, we do not need extra flags? This flag seems to be turning of some extra layers but I can't find official documentation for it? 

I need to be sure about this flag because when we do not use it, then we do not see speed ups between int8 and fp32 ...

Thanks!

**Comment by gfursin** [comment]
Hi again @guomingz! 
We completed evaluation of your artifact on different platforms including Skylake in AWS and Google cloud and confirmed numbers from your paper (nearly exact match). I added best points to the cKnowledge.org/request-results . You can change dimension 1 (X) to show "Inference throughput" and you will see 465 images/sec for int8 ResNet 50 on c5.9xlarge. 
The only thing remaining is to tell us what is the difference in "caffe test" when using or not using "-phase TEST" flag. Thanks a lot!

**Comment by gfursin** [comment]
But having CK really helped simplify installation, experiments and results sharing - it was very straightforward to run your code on Azure, AWS and Google cloud ...

**Comment by guomingz** [comment]
Hi @gfursin  sorry for later response.
The flag '-phase TEST' is not used for `caffe test` commands but for `caffe time` commands. As we measure the latency/throughput by using `caffe time` entry and our int8 implementation is only valid during the forward phase, so we  add the `-phase TEST` flag to tell the caffe don't execute backward operations. And the `caffe test` command is only used for accuracy measurement.

When we pass the `-phase TEST`  into the Intel caffe, it do execute some layer fusion to get better performance.

**Comment by gfursin** [comment]
No worries, @guomingz, and thanks for your reply (by the way, sorry for a typo - I meant "caffe time", not "caffe test") ... Ok, I see, so the main difference in timing when using "caffe time" with or without "-phase TEST" is likely due to layer fusion during "-phase TEST". Thanks.
