### ISSUE TITLE
Measure accuracy on Inception-v3

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-request-asplos18-caffe-intel#9]
- [x] Install [Intel Caffe from the ReQuEST branch](https://github.com/ctuning/ck-request-asplos18-caffe-intel#install-intel-caffe-from-the-request-artifact-branch).
- [x] Install or detect the full [ImageNet validation dataset](https://github.com/ctuning/ck-request-asplos18-caffe-intel#install-imagenet-validation-datasets).
- [x] Install the [Inception-v3 model](https://github.com/ctuning/ck-request-asplos18-caffe-intel#inception-v3).
- [x] Run the following while selecting all the above if prompted:
```
$ ck benchmark program:caffe \
  --cmd_key=test_cpu --repetitions=1 --env.CK_CAFFE_BATCH_SIZE=64 \
  --record --record_repo=local \
  --record_uoa=ck-request-asplos18-caffe-intel-accuracy-inceptionv3 \
  --tags=request,request-asplos18,caffe,intel,accuracy,inceptionv3
...
{
  "accuracy/top-1": ?, 
  "accuracy/top-5": ?,
  "post_processed": "yes"
}
```

**Comment by Chunosov** [comment]
Here is PR for Inception-v3 F32 package:  https://github.com/dividiti/ck-caffe/pull/133

**Comment by Chunosov** [comment]
## float32

Resolution | Top-1 | Top-5
------|--------------|-------------
320|0.753941|0.923415
Intel|0.7544|0.9236

## int8
Resolution | Top-1 | Top-5
------|--------------|-------------
320|0.753281|0.923275
Intel|0.7531|0.9233

**NB:** The "Intel" results are from Table 3 in the submitted abstract.

**Comment by Chunosov** [comment]
But evaluation of int8 have taken a terrible long time:
```
"execution_time_with_module": 8355.747189998627,
```
About 2.5h...
While for float32 it is about 15min

**Comment by psyhtest** [comment]
If we round off to 4 significant digits, we get very close. Not bad given that the weights conversion process is stochastic.

## float32

Resolution | Top-1 | Top-5
------|--------------|-------------
320|0.7534|0.9234
Intel|0.7544|0.9236

## int8
Resolution | Top-1 | Top-5
------|--------------|-------------
320|0.7533|0.9233
Intel|0.7531|0.9233

**Comment by Chunosov** [comment]
Here are full experiment results
```
ck zip local:experiment:ck-request-asplos18-caffe-intel-accuracy-inceptionv3
ck zip local:experiment:ck-request-asplos18-caffe-intel-accuracy-inceptionv3-i8
```
[ck-request-asplos18-caffe-intel-accuracy-inceptionv3.zip](https://github.com/ctuning/ck-request-asplos18-caffe-intel/files/1751652/ck-request-asplos18-caffe-intel-accuracy-inceptionv3.zip)
[ck-request-asplos18-caffe-intel-accuracy-inceptionv3-i8.zip](https://github.com/ctuning/ck-request-asplos18-caffe-intel/files/1751653/ck-request-asplos18-caffe-intel-accuracy-inceptionv3-i8.zip)

**Comment by psyhtest** [comment]
Here's the [experimental data](https://github.com/ctuning/ck-request-asplos18-caffe-intel/files/1825759/ck-request-asplos18-caffe-intel-accuracy-inception-v3.zip) obtained when following the [README](https://github.com/ctuning/ck-request-asplos18-caffe-intel#inception-v3) and using:
```
$ ck benchmark program:caffe \
--cmd_key=test_cpu --repetitions=1 \
--env.CK_CAFFE_BATCH_SIZE=64 \
--record --record_repo=local \
--record_uoa=ck-request-asplos18-caffe-intel-accuracy-inception-v3 \ 
--tags=request,request-asplos18,caffe,intel,accuracy,inception-v3,vfp32,vfloat32

$ ck benchmark program:caffe \
--cmd_key=test_cpu --repetitions=1 \
--env.CK_CAFFE_BATCH_SIZE=64 \
--record --record_repo=local \
--record_uoa=ck-request-asplos18-caffe-intel-accuracy-inception-v3-i8 \
--tags=request,request-asplos18,caffe,intel,accuracy,inception-v3,vi8,vint8

$ ck zip local:experiment:ck-request-asplos18-caffe-intel-accuracy-inception-v3* \
--archive_name=~/ck-request-asplos18-caffe-intel-accuracy-inception-v3.zip
```

Precision | Top 1 | Top 5
-|-|-
`fp32` | 0.753941 | 0.923415
`int8` | 0.753001 | 0.923115

**Comment by psyhtest** [comment]
The `fp32` accuracy figures are exactly reproducible. However, the `int8` ones seem to depend on the conversion. We could perhaps save results from such a conversion as e.g. `package:caffemodel-resnet50-intel-i8-snapshot`?

**Comment by Chunosov** [comment]
What should be in this package?

**Comment by psyhtest** [comment]
I was thinking about storing some quantised models, that including the usual links to download the weights and provide the converted `prototxt` files. Now, it seems that some conversions are a bit better than others but it doesn't matter much - any reasonable conversion will do for this purpose.
